export const roles = [
  "SUPER_ADMIN",
  "ADMIN",
  "PROJECT_MANAGER",
  "HR_MANAGER",
  "FINANCE_MANAGER",
  "EMPLOYEE",
  "CLIENT",
] as const;

export type AppRole = (typeof roles)[number];

export const permissions = {
  users: ["read", "create", "update", "delete", "invite"],
  clients: ["read", "create", "update", "delete"],
  projects: ["read", "create", "update", "delete", "assign"],
  tasks: ["read", "create", "update", "delete", "comment"],
  hr: ["read", "create", "update", "approve"],
  finance: ["read", "create", "update", "approve", "delete"],
  invoices: ["read", "create", "update", "send"],
  reports: ["read", "export"],
  documents: ["read", "upload", "delete"],
  settings: ["read", "update"],
} as const;

export type PermissionResource = keyof typeof permissions;
export type PermissionAction<T extends PermissionResource = PermissionResource> =
  (typeof permissions)[T][number];
export type PermissionKey = `${PermissionResource}:${string}`;

export const rolePermissionMatrix: Record<AppRole, PermissionKey[]> = {
  SUPER_ADMIN: [
    "users:read",
    "users:create",
    "users:update",
    "users:delete",
    "users:invite",
    "clients:read",
    "clients:create",
    "clients:update",
    "clients:delete",
    "projects:read",
    "projects:create",
    "projects:update",
    "projects:delete",
    "projects:assign",
    "tasks:read",
    "tasks:create",
    "tasks:update",
    "tasks:delete",
    "tasks:comment",
    "hr:read",
    "hr:create",
    "hr:update",
    "hr:approve",
    "finance:read",
    "finance:create",
    "finance:update",
    "finance:approve",
    "finance:delete",
    "invoices:read",
    "invoices:create",
    "invoices:update",
    "invoices:send",
    "reports:read",
    "reports:export",
    "documents:read",
    "documents:upload",
    "documents:delete",
    "settings:read",
    "settings:update",
  ],
  ADMIN: [
    "users:read",
    "users:create",
    "users:update",
    "users:invite",
    "clients:read",
    "clients:create",
    "clients:update",
    "projects:read",
    "projects:create",
    "projects:update",
    "projects:assign",
    "tasks:read",
    "tasks:create",
    "tasks:update",
    "hr:read",
    "hr:update",
    "hr:approve",
    "finance:read",
    "finance:create",
    "finance:update",
    "invoices:read",
    "invoices:create",
    "invoices:update",
    "reports:read",
    "reports:export",
    "documents:read",
    "documents:upload",
    "settings:read",
  ],
  PROJECT_MANAGER: [
    "clients:read",
    "projects:read",
    "projects:update",
    "projects:assign",
    "tasks:read",
    "tasks:create",
    "tasks:update",
    "tasks:comment",
    "reports:read",
    "documents:read",
    "documents:upload",
  ],
  HR_MANAGER: [
    "users:read",
    "hr:read",
    "hr:create",
    "hr:update",
    "hr:approve",
    "reports:read",
    "documents:read",
    "documents:upload",
  ],
  FINANCE_MANAGER: [
    "clients:read",
    "finance:read",
    "finance:create",
    "finance:update",
    "finance:approve",
    "invoices:read",
    "invoices:create",
    "invoices:update",
    "invoices:send",
    "reports:read",
    "reports:export",
  ],
  EMPLOYEE: [
    "projects:read",
    "tasks:read",
    "tasks:create",
    "tasks:update",
    "tasks:comment",
    "documents:read",
  ],
  CLIENT: [
    "projects:read",
    "invoices:read",
    "documents:read",
  ],
};

